# Generated by Django 4.2.2 on 2023-06-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kode',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Code of operator'),
        ),
    ]
