# Generated by Django 4.2.2 on 2023-06-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_kode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
