# Generated by Django 4.2.2 on 2023-06-26 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_message_idclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='idclient',
            new_name='idclients',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='filternumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
