# Generated by Django 4.2.2 on 2023-06-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_idclient_message_idclients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='filternumber',
        ),
    ]
