# Generated by Django 4.2.2 on 2023-06-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_newsletter_filternumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(blank=True, help_text='Name of NewsLetter', max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
