# Generated by Django 4.2.2 on 2023-06-26 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_newsletter_title_alter_newsletter_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='idclients',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='filternumber',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='idclients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
