# Generated by Django 4.2.2 on 2023-06-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_newsletter_filternumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='filternumber',
            field=models.CharField(choices=[], max_length=1, null=True),
        ),
    ]
