# Generated by Django 4.2.2 on 2023-06-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_newsletter_filternumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kode',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Code of operator'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер телефона '),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='filternumber',
            field=models.CharField(choices=[(928, 928)], max_length=1, null=True),
        ),
    ]
