# Generated by Django 4.2.2 on 2023-06-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_customuser_kode_alter_customuser_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Status',
            field=models.BooleanField(help_text='True = Send,False = NOT', verbose_name='statusmessage'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='filternumber',
            field=models.CharField(choices=[('928', '928')], max_length=3, null=True),
        ),
    ]
